theme = "monokai_pro_ristretto"

[editor]
true-color = true
line-number = "relative"
default-line-ending = "lf"
rulers = [ 80 ]

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[keys.insert]
C-space = "completion"
